### ISSUE TITLE
let dt_* functions more like dplyr

### ISSUE THREAD

**Issue by hope-data-science** [gdemin/maditr#5]
Awesome piece! Great syntax for data.table. But maybe some adjustment for the in-place operation might help. For instance, using dt_mutate could not yield any results unless we use head() or print(), why not just add %>% .[] and show it to make it more like dplyr, or even use as_tibble() to show it in a new way. I think change in place might be useless for pipe work.
Again, thank you for all the awesome efforts you have made to the community!

**Comment by hope-data-science** [comment]
I just hope dt_mutate would be more like mutate in dplyr, this might be the point. I see why you don't even need to use dplyr, awesome way to trade between performance and syntax. Also, is there a correspondent function for count or top_n? I think they are quite common in data manipulation.

**Comment by gdemin** [comment]
Thank you for you warm feedback.

> I think change in place might be useless for pipe work.

Sorry, but I can't do it because we lose performance if we will copy entire data.table during operations. If performance is not an issue for you then you can consider `dtplyr` package which is data.table backend for `dplyr`. 

>is there a correspondent function for count or top_n?

By now there are no such functions but I will consider to add them in the future versions.

**Comment by gdemin** [comment]
Added in version 0.6.3
